apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-agent-deployment
  labels:
    app: {{ .Chart.Name }}-agent
    role: agent
spec:
  replicas: {{ .Values.agent.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-agent
        role: agent
    spec:
      {{- if .Values.agent.persistence.enabled }}
      volumes:
        - name: homego-vol
          persistentVolumeClaim:
            claimName: {{ .Values.agent.persistence.homego.name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-agent
          image: "{{ .Values.agent.image.repository }}:v{{default .Chart.AppVersion .Values.app.version}}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
          env:
          - name: GO_SERVER_URL
          {{- if .Values.agent.goServerUrl }}
            value: {{ .Values.agent.goServerUrl }}
          {{- else }}
            value: "https://{{ .Values.server.service.name }}:{{ .Values.server.service.httpsPort }}/go"
          {{- end }}

          {{- if .Values.agent.agentAutoRegisterKey }}
          - name: AGENT_AUTO_REGISTER_KEY
            value: {{ .Values.agent.agentAutoRegisterKey }}
          {{- end }}
          {{- if .Values.agent.agentAutoRegisterResources }}
          - name: AGENT_AUTO_REGISTER_RESOURCES
            value: {{ .Values.agent.agentAutoRegisterResources }}
          {{- end }}
          {{- if .Values.agent.agentAutoRegisterEnvironemnts }}
          - name: AGENT_AUTO_REGISTER_ENVIRONMENTS
            value: {{ .Values.agent.agentAutoRegisterEnvironemnts }}
          {{- end }}
          {{- if .Values.agent.agentAutoRegisterHostname }}
          - name: AGENT_AUTO_REGISTER_HOSTNAME
            value: {{ .Values.agent.agentAutoRegisterHostname }}
          {{- end }}
          {{- if .Values.agent.persistence.enabled }}
          volumeMounts:
          - name: homego-vol
            mountPath: /home/go
          {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.agent.nodeSelector | indent 8 }}
    {{- end }}
