apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.agent.name }}
  labels:
    app: {{ template "name" . }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        role: agent
    spec:
      containers:
        - name: {{ .Values.agent.name }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          env:
          - name: GO_SERVER_URL
          {{- if .Values.agent.goServerUrl }}
            value: {{ .Values.agent.goServerUrl }}
          {{- else }}
            value: "https://{{ .Values.server.service.name }}:{{ .Values.server.service.httpsPort }}/go"
          {{- end }}
          - name: AGENT_AUTO_REGISTER_KEY
            value: {{ .Values.agent.agentAutoRegisterKey }}
          - name: AGENT_AUTO_REGISTER_RESOURCES
            value: {{ .Values.agent.agentAutoRegisterResources }}
          - name: AGENT_AUTO_REGISTER_ENVIRONMENTS
            value: {{ .Values.agent.agentAutoRegisterEnvironemnts }}
          - name: AGENT_AUTO_REGISTER_HOSTNAME
            value: {{ .Values.agent.agentAutoRegisterHostname }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
