{{- if .Values.server.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.server.ingress.name }}
  labels:
    app: {{ template "name" . }}
  annotations:
    {{- range $key, $value := .Values.server.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  backend:
    serviceName: {{ .Values.server.name }}-service
    servicePort: {{ .Values.server.service.httpPort }}
  rules:
    {{- range $host := .Values.server.ingress.hosts }}
    - host: {{ $host }}
  {{- end -}}
{{- end -}}
